SELECT "dim_ap_ce_xso_comp"."billing_language_name" AS "billing_language_n",
  "dim_ap_ce_xso_comp"."committed_hours" AS "committed_hours",
  "dim_ap_ce_xso_comp"."date" AS "date",
  "dim_ap_ce_xso_comp"."date_dmy" AS "date_dmy",
  "dim_ap_ce_xso_comp"."ds" AS "ds__dim_ap_ce_xso_",
  "dim_ap_ce_xso_comp"."employee_type" AS "employee_type__dim",
  "dim_ap_ce_xso_comp"."interval_list" AS "interval_list",
  "dim_ap_ce_xso_comp"."maxbill_id" AS "maxbill_id__dim_ap",
  "dim_ap_ce_xso_comp"."organisation" AS "organisation__dim_",
  "dim_ap_ce_xso_comp"."planning_group" AS "planning_group__di",
  "dim_ap_ce_xso_comp"."primary_business_unit" AS "primary_business_u",
  "dim_ap_ce_xso_comp"."staffing_group" AS "staffing_group__di",
  "dim_ap_ce_xso_comp"."stf_version" AS "stf_version__dim_a",
  "dim_ap_ce_xso_comp"."work_city" AS "work_city__dim_ap_"
FROM "si"."dim_ap_ce_xso_compliance_hours" "dim_ap_ce_xso_comp"
where ds = '<LATEST_DS:dim_ap_ce_xso_compliance_hours>'
SELECT "dim_ap_ce_xso_ltf"."alt_id" AS "alt_id",
  "dim_ap_ce_xso_ltf"."billable_role" AS "billable_role",
  "dim_ap_ce_xso_ltf"."billing_language_name" AS "billing_language_n",
  "dim_ap_ce_xso_ltf"."ds" AS "ds__dim_ap_ce_xso_",
  "dim_ap_ce_xso_ltf"."employee_type" AS "employee_type__dim",
  "dim_ap_ce_xso_ltf"."internal_comments" AS "internal_comments",
  "dim_ap_ce_xso_ltf"."maxbill_id" AS "maxbill_id",
  "dim_ap_ce_xso_ltf"."new_hire_training_fte_avg" AS "new_hire_training_",
  "dim_ap_ce_xso_ltf"."new_hire_training_fte_cb" AS "new_hire_training1",
  "dim_ap_ce_xso_ltf"."new_hire_training_hours" AS "new_hire_training2",
  "dim_ap_ce_xso_ltf"."organization" AS "organization",
  "dim_ap_ce_xso_ltf"."period" AS "period",
  "dim_ap_ce_xso_ltf"."period_type" AS "period_type",
  "dim_ap_ce_xso_ltf"."planning_group" AS "planning_group__di",
  "dim_ap_ce_xso_ltf"."po" AS "po__dim_ap_ce_xso_",
  "dim_ap_ce_xso_ltf"."primary_business_unit" AS "primary_business_u",
  "dim_ap_ce_xso_ltf"."production_fte_avg" AS "production_fte_avg",
  "dim_ap_ce_xso_ltf"."production_fte_cb" AS "production_fte_cb",
  "dim_ap_ce_xso_ltf"."production_hours" AS "production_hours",
  "dim_ap_ce_xso_ltf"."resiliency" AS "resiliency__dim_ap",
  "dim_ap_ce_xso_ltf"."staffing_group" AS "staffing_group__di",
  "dim_ap_ce_xso_ltf"."total_fte_avg" AS "total_fte_avg",
  "dim_ap_ce_xso_ltf"."total_fte_cb" AS "total_fte_cb",
  "dim_ap_ce_xso_ltf"."total_hours" AS "total_hours",
  "dim_ap_ce_xso_ltf"."work_city" AS "work_city__dim_ap_",
  "dim_ap_ce_xso_ltf"."ww_year" AS "ww_year__dim_ap_ce"
FROM "si"."dim_ap_ce_xso_ltf" "dim_ap_ce_xso_ltf"
where ds = '<LATEST_DS:dim_ap_ce_xso_ltf>'
