SELECT "dim_ap_ce_xso_stf_"."billing_language_name" AS "billing_language_name",
  "dim_ap_ce_xso_stf_"."ds" AS "ds",
  "dim_ap_ce_xso_stf_"."employee_type" AS "employee_type",
  "dim_ap_ce_xso_stf_"."final_hours_guidance" AS "final_hours_guidance",
  "dim_ap_ce_xso_stf_"."guidance_date" AS "guidance_date",
  "dim_ap_ce_xso_stf_"."interval_hour" AS "interval_hour",
  "dim_ap_ce_xso_stf_"."maxbill_alternate_id" AS "maxbill_alternate_id",
  "dim_ap_ce_xso_stf_"."maxbill_hash" AS "maxbill_hash",
  "dim_ap_ce_xso_stf_"."maxbill_id" AS "maxbill_id",
  "dim_ap_ce_xso_stf_"."organisation" AS "organisation",
  "dim_ap_ce_xso_stf_"."planning_group" AS "planning_group",
  "dim_ap_ce_xso_stf_"."po" AS "po",
  "dim_ap_ce_xso_stf_"."primary_business_unit" AS "primary_business_unit",
  "dim_ap_ce_xso_stf_"."resiliency" AS "resiliency",
  "dim_ap_ce_xso_stf_"."staffing_group" AS "staffing_group",
  "dim_ap_ce_xso_stf_"."stf_version" AS "stf_version",
  "dim_ap_ce_xso_stf_"."work_city" AS "work_city",
  "dim_ap_ce_xso_stf_"."ww_week" AS "ww_week",
  "dim_ap_ce_xso_stf_"."ww_year" AS "ww_year"
FROM "si"."dim_ap_ce_xso_stf_guidance" "dim_ap_ce_xso_stf_"
where ds = '<LATEST_DS:dim_ap_ce_xso_stf_guidance>'
